namespace ProjectF.Presentation.Common
{
    using UnityEngine;

    /// <summary>
    /// A pond volume: on player entry the fishing UI (Stage 9's
    /// FishingPresenter wiring) targets this pond's id. The chain owns ALL
    /// pond truth (slots, occupancy, expiry) — this component only tells the
    /// client WHICH pond to act on (FishingAction(pondId)).
    /// Generated by the Stage 8 prefab generator with pondId 1 (village pond,
    /// data/pond.csv scene_id 4 = FarmPlot).
    /// </summary>
    [RequireComponent(typeof(BoxCollider2D))]
    public sealed class FishingSpot : MonoBehaviour
    {
        [SerializeField]
        private int pondId = 1;

        public int PondId => pondId;

        /// <summary>Editor tooling hook (Stage 8 generators).</summary>
        public void Configure(int newPondId) => pondId = newPondId;

        private void Reset()
        {
            GetComponent<BoxCollider2D>().isTrigger = true;
        }
    }
}
